### ISSUE TITLE
Reaproveitamento de código

### ISSUE THREAD

**Issue by brunowego** [zenorocha/ama#1]
Você costuma reaproveitar os componentes que você desenvolve em outros projetos ou prefere refazer do zero utilizando a experiência que teve nos projetos passados?

Pessoalmente, claro se tiver tempo no projeto, prefiro desenvolver do zero, mas claro, reaproveitando toda a experiência nos projetos passados.

**Comment by zenorocha** [comment]
Depende muito do cenário. Se for algo da empresa, procuro sempre criar uma vez só e reaproveitar. 

Mas no lado pessoal....eu gostaria de dizer que reaproveito tudo mas a verdade é que eu gosto de fazer as coisas do zero. Se tem uma coisa que eu aprendi com o @tj é que [não existe nada de errado em refazer a roda](https://www.youtube.com/watch?v=wxDBF3OOaRA). Você aprende muito quando faz isso, por mais que seja um problema já resolvido por muita gente.

**Comment by brunowego** [comment]
Exato @zenorocha :+1: 

Obrigado!

**Comment by erichnascimento** [comment]
:+1:

**Comment by giovannipds** [comment]
Top. :+1:

**Comment by douglasnev3s** [comment]
:+1:
