### ISSUE TITLE
Indicações de livros

### ISSUE THREAD

**Issue by lehcosta** [zenorocha/ama#10]
@zenorocha quais livros você já leu sobre desenvolvimento que você indicaria?

**Comment by zenorocha** [comment]
Livros nunca foram minha fonte de estudo quando o assunto é desenvolvimento. Por algum motivo, eu só tenho paciência de estudar programação na prática.

Isso não quer dizer que eu odeio livros. Inclusive, aqui tem uma [lista de livros que eu li recentemente](https://gist.github.com/zenorocha/c6210790828657e245d9).

Nesse momento eu estou numa pegada forte em audiobooks. Já ouvi 3 pela [Audible](http://www.audible.com/), todos sobre empreendedorismo.
