### ISSUE TITLE
Dica para quem está querendo sair da zona do conforto

### ISSUE THREAD

**Issue by rubens-shoji** [zenorocha/ama#11]
Olá Zeno, agradeço a oportunidade que você abriu para comunidade, sempre acompanho seus feitos no twitter rsrs. Que dica você daria para alguém que quer sair da zona de conforto e partir para algo mais desafiador como por exemplo uma oportunidade legal no exterior?

Abraço!

**Comment by zenorocha** [comment]
O primeiro passo você já deu. Já sabe o que quer no futuro.

O segundo passo é reconhecer o que você tá fazendo HOJE pra alcançar aquilo.

Então, observa sua rotina e veja como pode encaixar algumas horas de estudo sobre esse assunto. 

Como funcionam os vistos no país que você quer morar? Quais são as principais empresas que você gostaria de trabalhar nesse país? Que tipo de habilidade técnica falta em você para entrar nessas empresas? Quais são os livros que você precisa ler pra preencher essa lacuna?

Você precisa de todas essas respostas na ponta da língua.

**Comment by kivervinicius** [comment]
:+1:

**Comment by zenorocha** [comment]
https://medium.com/@zenorocha/o-que-voc%C3%AA-est%C3%A1-esperando-f58bbc970054#.abmuyf55f
