### ISSUE TITLE
fluxo de trabalho com git

### ISSUE THREAD

**Issue by clarabatt** [zenorocha/ama#13]
Oi Zeno, desde que eu descobri o git eu tenho uma grande dúvida, qual o melhor jeito de trabalhar com ele? Se é fazendo um commit com várias alterações ou um commit por alteração. Obrigada pela oportunidade :]

**Comment by zenorocha** [comment]
Sempre tive essa dúvida e só aprendi depois de rejeitarem muitos pull requests meus.

Imagina que você tem uma tarefa "Redesign blog". A maioria das pessoas começa a programar e quando tudo tá pronto: `git commit -m "Redesigned blog"`

Isso é muito errado. Imagina que você quer reverter só um pedacinho dessa alteração toda? O único jeito seria reverter o commit inteiro. Ou então imagina que você queira dar um cherry pick de um pedacinho específico em outra branch? De novo, teria que fazer isso com o commit inteiro.

Minha estratégia é quebrar a task maior em subtasks. Cada um dessas subtasks é um commit. O pull request é quem conta a história toda.

Escrevi mais sobre isso [dois anos atrás](http://zenorocha.com/most-active-contributors-on-github). E o GitHub é outro que [internamente usa esse tipo de estratégia](https://github.com/blog/1124-how-we-use-pull-requests-to-build-github).

**Comment by ricardobarantini** [comment]
Tirou uma dúvida que eu tinha também. :+1:
