### ISSUE TITLE
Como é trabalhar na Liferay?

### ISSUE THREAD

**Issue by vandersondev** [zenorocha/ama#14]
Como as equipes são organizadas, quantos participantes por projeto/serviço e etc?
Poderia descrever como é o dia a dia?
O que usam de ferramentas?

Abraços.

**Comment by zenorocha** [comment]
Estou há mais de 3 anos na Liferay e posso dizer que o dia a dia é bem interessante.

Já visitei vários escritórios da empresa desde Chicago até Frankfurt. Cada um tem suas manias e características, mas os valores são sempre os mesmos. Também trabalhei em várias situações diferentes, desde remotamente no Rio de Janeiro, passando por morar no apartamento da empresa em Recife, até trocar de país pra viver aqui em Los Angeles. Entrei para trabalhar full-time em Engenharia, mas sempre fui pró-ativo e ajudo os departamentos de HR, Sales, Marketing, etc. Isso me deu a oportunidade de entender a empresa como pouquíssima gente consegue. E também de compreender que a rotina varia bastante dependendo do departamento/região que você trabalha.

Geralmente as equipes são pequenas e divididas por produtos, mas existem excessões. O produto principal, [Liferay Portal](https://www.liferay.com/community/liferay-projects/liferay-portal/overview), tem uma série de times por baixo. Existem times até para cuidar de um só módulo já que o projeto é bem grande.

A maioria das pessoas que eu trabalho são viciadas por produtividade assim como eu. Então existe um investimento bom em tooling. E quando eu digo investimento vai desde comprar a licença de alguma ferramenta que a gente achou legal até parar e desenvolver as nossas como é o caso do [NodeGH](https://github.com/node-gh).

Existe um senso de ownership sobre o que você tá trabalhando. Isso é bem legal e te motiva a fazer algo bem feito. Outra coisa que eu gosto é que a empresa tem um organograma bem flat. Todas as discussões são de igual pra igual. O time que eu trabalho hoje é um exemplo disso. Surgiu da ideia do @eduardolundgren e hoje estamos criando algo completamente separado e independente pra trocar essa ideia.

Enfim, é um constante aprendizado e não teria outro lugar que eu gostaria de estar agora.
