### ISSUE TITLE
What is your #1 productivity tip?

### ISSUE THREAD

**Issue by sindresorhus** [zenorocha/ama#15]

**Comment by flpms** [comment]
:+1:

**Comment by zenorocha** [comment]
Don't buy a video game

**Comment by jeremymarshall1** [comment]
Should have clarified WORK productivity.  I'm very productive in Minecraft and World of Warcraft

**Comment by zenorocha** [comment]
Yes! I'm more productive in Counter Strike and Battlefield :P

**Comment by jeremymarshall1** [comment]
I bet you I'm more productive than you at Counter Strike and Battlefield...

**Comment by zenorocha** [comment]
I bet you aren't

**Comment by jeremymarshall1** [comment]
Thems fighting words...

**Comment by zenorocha** [comment]
![](https://pbs.twimg.com/media/BxUghm1CUAEmELG.jpg)
