### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by sindresorhus** [zenorocha/ama#17]

**Comment by zenorocha** [comment]
[jQuery Boilerplate](https://github.com/jquery-boilerplate/jquery-boilerplate/).

It was my first open source project back in 2011.

At that time, I wanted build a jQuery plugin but there was a lot of different patterns out there. So inspired by @paulirish's [HTML5 Boilerplate](https://html5boilerplate.com/), I decided to give it a shot.

<a href="http://jqueryboilerplate.com"><img src="https://cloud.githubusercontent.com/assets/398893/10648770/5118f8d0-77f5-11e5-81ca-971a26e8ebe8.jpg"></a>

I put this little site online and nobody showed up on the first day.

On the second day, @smashingmagazine tweeted it.

<a href="https://twitter.com/smashingmag/status/95456628412915712"><img width="597" alt="screen shot 2015-10-21 at 1 04 42 pm" src="https://cloud.githubusercontent.com/assets/398893/10648623/570c1f66-77f4-11e5-83c2-e1aeae079657.png"></a>

What a successful story to tell others, right? Nope.

The thing is, I had never built a jQuery plugin before and I wanted to establish the best pattern for everybody to use it. I was super naive and @rwaldron taught me a very though lesson.

<a href="https://github.com/jquery-boilerplate/jquery-boilerplate/pull/10"><img width="798" alt="screen shot 2015-10-21 at 1 09 33 pm" src="https://cloud.githubusercontent.com/assets/398893/10648727/08b51ede-77f5-11e5-9c89-2cc24ee7c94b.png"></a>

I was paralyzed and felt like shit.

But in the end, I accepted that PR, @addyosmani showed up, and we rebuilt that project.

Now, I see how helpful this episode was. Those guys were mentors to me and helped me shape who I am today.

**Comment by giovannipds** [comment]
Wow... inspiring! :+1: =O
