### ISSUE TITLE
Open Source Advocacy in LA

### ISSUE THREAD

**Issue by jdorfman** [zenorocha/ama#19]
Hey @zenorocha,

I was surprised (and happy) to learn that the author of Clipboard.js (great project btw) also lived in Los Angeles.  My question to you is what do you find difficult about being a Developer / Open Source Advocate in Los Angeles?  What advice would you give to other advocates in Los Angeles?

Thanks!

**Comment by zenorocha** [comment]
I'd rather mention the huge amount of advantages that we have by being in LA.
1. There's a decent international airport with direct flights to Europe, South America and other continents.
2. It's 1 hour away from Silicon Valley and not that far from East Coast by plane.
3. Plenty of big companies also have offices here.
4. Pretty vibrant startup community growing in Santa Monica.

I lived in Brazil and things can be way harder down there. I think there's some tremendous opportunity to tackle here.

I'm not saying that LA is the best city in the world. I'm just saying that if there's **one thing that you don't need to care is where you are located**.

**Comment by zenorocha** [comment]
Thanks for asking @jdorfman. Looking forward to meet you in person at some local meetup ;)

**Comment by jdorfman** [comment]
> Thanks for asking @jdorfman. Looking forward to meet you in person at some local meetup ;)

Awesome answer Thank you @zenorocha 

> Looking forward to meet you in person at some local meetup ;)

Ditto.  If you or anyone you know ever need a space, MaxCDN can host. =)

**Comment by zenorocha** [comment]
Great ;D
