### ISSUE TITLE
O que é ser Engineer/Advocate Front-End? 

### ISSUE THREAD

**Issue by ghost** [zenorocha/ama#21]
Em suas palavras, o que é ser Engineer e Advocate Front-End? Qual o perfil, dia a dia, qual o papel em um projeto?

**Comment by zenorocha** [comment]
Cada empresa e indivíduo tem uma visão sobre esses termos, vou expressar a minha mas não quer dizer que esteja certa.
- **Engineer:** não é apenas alguém que sabe desenvolver. Escrever código qualquer sobrinho faz. Agora entender como as coisas funcionam a fundo, tomando decisões baseadas em arquitetura e alto nível de entendimento em design de software. Pra mim isso é o que diferencia um Developer qualquer de um Engineer.
- **Advocate (Evangelist):** é alguém com conhecimento técnico e que representa os interesses dos desenvolvedores dentro de uma empresa. Inspirando e equipam outros desenvolvedores internos ou externos a utilizarem determinada plataforma. Não é marketing, não é vendas, não é RH. E ainda sim, envolve todos esses departamentos.

**Comment by ghost** [comment]
:metal: :+1:
