### ISSUE TITLE
O que você acha desse meu projeto ? 

### ISSUE THREAD

**Issue by guisouza** [zenorocha/ama#22]
http://www.github.com/guisouza/dss

**Comment by zenorocha** [comment]
Acho um projeto incrível e ousado. Você está no caminho certo, continue investindo em demos e documentação.

Em termos de praticabilidade, o projeto ainda tem um caminho bem grande a percorrer. Converter e renderizar CSS com JavaScript em runtime, apesar de bem legal ainda é questionável em termos de produção. Talvez algo na linha do [PostCSS](https://github.com/postcss/postcss) seja mais paupável.

Ainda sim, mete bala. O React foi absurdamente mal aceito no início, quebrou vários paradigmas e olha como tá hoje.

Admiro sua persistência e sagacidade meu irmão.
