### ISSUE TITLE
Qual a sua maneira de estudar ?

### ISSUE THREAD

**Issue by andersoonweb** [zenorocha/ama#23]
Sempre temos uma técnica pra absolver  o conteúdo mais rápido, o que você faz ?

**Comment by zenorocha** [comment]
Não acho que o lance está em absorver conteúdo mais rápido, mas sim absorver BEM. Acredito fielmente que uma base boa pode te levar a qualquer lugar. Então, minha maneira de estudar está bem relacionada a isso. 

Minha técnica se chama auto sabotagem. Se existe algo que eu quero muito aprender, eu invento situações que me forcem a estudar aquilo.

Foi assim com HTML5: Em 2009/2010, eu trabalhava com Flash e estava super interessado em HTML5. Fazia faculdade, trabalhava e fazia freela. Não tinha absolutamente nenhum segundo pra estudar qualquer coisa extra. O jeito que eu encontrei foi submetendo uma palestra sobre HTML5 mesmo sem nem saber a fundo o que era. Quando aceitaram, tive que me forçar a estudar. Era isso ou ia fazer papel de bobo na frente de todo mundo. Então meti a cara e estudei.

Outro exemplo recente: Queria muito experimentar Browserify e ES2015 pra valer em um projeto real. Então escrevi o clipboard.js usando os dois. Não queria fazer papel de bobo lançando algo pro público que não fosse bem escrito. Então tive que meter a cara e estudar.

A maioria das minhas talks, blogpost, e projetos open source são desculpas para aprender algo que eu ainda não sei. Esse é a minha maneira.

**Comment by andersoonweb** [comment]
bom @zenorocha ! Também estou seguindo essa linha. valeu!
