### ISSUE TITLE
What's the thing you like the most and the one you like less in Polymer?

### ISSUE THREAD

**Issue by Granze** [zenorocha/ama#24]

**Comment by zenorocha** [comment]
The thing I like the most is the API. I'm a big fan of declarative approaches, I think it makes way easier for beginners to learn. And the imperative part is also pretty straightforward.

The one thing I like less in Polymer is browser support. I understand that it's super hard to polyfill most of the things but there should be more investment on this. The way I see it, this is one of the biggest reasons why adoption by the general public is so slow.
