### ISSUE TITLE
Qual foi sua maior dificuldade em morar fora do Brasil

### ISSUE THREAD

**Issue by kivervinicius** [zenorocha/ama#25]
E como aconteceu isso? Recebeu alguma ajuda? Tenho muita vontade em morar fora, principalmente pelo networking, tenho conhecimento intermediário de inglês mas nada mto avançado, estou na zona de conforto chamado(único front-end da empresa) e meu salário é bom, mas não me sinto satisfeito como desenvolvedor, qual sua dica para isso e como eu poderia tentar me livrar dessas correntes(obs. já sou casado, o que dificulta as coisas).

**Comment by zenorocha** [comment]
Minha maior dificuldade em morar fora do Brasil é, e sempre será, ficar longe da família.

O resto já está respondido em https://github.com/zenorocha/ama/issues/11
