### ISSUE TITLE
Até que ponto você acredita que compensa re-inventar a roda?

### ISSUE THREAD

**Issue by kivervinicius** [zenorocha/ama#26]
Eu gosto muito de fazer isso, mesmo já existindo soluções(sempre existe, até melhor) mas cheguei em um momento que não sei se o que faço está correto apesar de aumentar meu conhecimento, eu utilizo muito destas ferramentas que faço em produção, isso poderia prejudicar em algo?

**Comment by zenorocha** [comment]
Pra mim re-inventar a roda significa resolver um problema que já foi amplamente resolvido. Ao fazer isso você tem a chance de aprender muito e não vejo como aprendizado poderia prejudicar alguma coisa.

Se o que você está produzindo não está correto, então não fiz sentido usar em produção. Você tem que equilibrar o que é bom pra você com o que é bom para o projeto.

**Comment by kivervinicius** [comment]
:+1:
