### ISSUE TITLE
Combinar libs e plugins na produção?

### ISSUE THREAD

**Issue by Soufraz** [zenorocha/ama#27]
O browserdiet fala da combinação de múltiplos arquivos css ou js. Mas sempre vejo a galera unificando menu.css + sidebar.css + footer.css e coisas do tipo. Mas nunca vi (pelo menos EU nunca vi) nenhum projeto combinando o font-awesome.css + bootstrap.css e coisas do tipo.
Combinar ou não combinar esses caras?

**Comment by zenorocha** [comment]
Não existe motivo para não combinar eles.
