### ISSUE TITLE
Como você aprendeu inglês?

### ISSUE THREAD

**Issue by ghost** [zenorocha/ama#3]
Olá Zeno, gostaria de saber como você aprendeu inglês ^^.

**Comment by zenorocha** [comment]
Meu pai sempre bateu na tecla de aprender inglês. Me colocou em uma escola bem simples aos 10 anos e fiquei lá até os 14 ou 15. Eu nunca dei muita bola, afinal nenhum jovem gosta de estudar.

Mas acho que foi algo bem natural. Sempre gostei de música em inglês, então ia no letras.mus.br ou vagalume pra pegar a letra e entender o que se falava. Desde pequeno com computador em casa, tudo o que eu queria fazer era jogar. Todos os jogos eram em inglês. Mesma coisa com seriados, adorava Lost mas nem sempre encontrava legenda.

Hoje vejo que isso foi um diferencial enorme na minha carreira e agradeço muito meu pai por ter dito essa visão. Mesmo sem grana ele sempre se esforçou pra manter a gente no inglês.

**Comment by ghost** [comment]
Muito legal.

Comigo está sendo um pouco diferente mas espero um dia chegar a fluência. Ouço bastante músicas e vejo muitas séries agora, consegui acordar sobre a importância do inglês "a tempo". 

Vlw Zeno.

**Comment by zenorocha** [comment]
Nunca é tarde @alvesnatan. Se você se dedicar bastante e treinar, já já vai estar bem mais confortável.

**Comment by giovannipds** [comment]
:+1:

**Comment by miguelgraz** [comment]
Uma rápida opinião pessoal é que chegando a um determinado nível de domínio da língua vale muito a pena se colocar "sob pressão", trabalhar num ambiente em que só se fala inglês, tentar passar um tempo fora e _precisar_ se virar com inglês, esse tipo de coisa, acredito que essas atitudes te forçam a evoluir num ritmo bem acelerado.

**Comment by zenorocha** [comment]
Exatamente @miguelgraz! Tem que se forçar a sair da zona de conforto. Eu sempre digo isso e é subestimado pela maioria das pessoas. 

Inclusive, esse foi um dos motivos que me fez sair da Globo para trabalhar na Liferay. Sabia que por ser uma empresa global eu ia ter acesso a discussões globais também.

Você pode fazer 5 anos de curso, assistir 27 temporadas de Friends sem legenda. E isso ainda não vai ser equivalente a 1 mês morando fora, trabalhando com pessoas de outros países.

**Comment by miguelgraz** [comment]
Que bom saber que não sou o único com essa opinião @zenorocha, tu colocou muito melhor o que eu estava tentando exemplificar :smiley:

**Comment by leonardofaria** [comment]
concordo com o @zenorocha e o @miguelgraz.

não importa o quanto o seu inglês é bom o ruim. quando você se força você aprende inglês de um jeito ou de outro. 

estou a um pouco mais de um mês no canadá e é isso aí

**Comment by ghost** [comment]
:+1:
