### ISSUE TITLE
Jquery, Angularjs e Polymer

### ISSUE THREAD

**Issue by fqmonte** [zenorocha/ama#31]
Fala Zeno, parabéns pela iniciativa do "Ask" e obrigado pela oportunidade.

Então, sabe aquele dev-design-ops-ninja-mutante, não no seu nível e com duvidas quanto a usar, materialize, bootstrap, bootstrap com material design e etc. Então organizei um Goolge I/O aqui na cidade e a galera pirou com o Polymer. E já tinha um grupo migrando para o Angularjs, impressionante ver que na maior parte são dev de .NET, e nem tantos do open (Pyhton, PHP, Ruby, Java e etc). Então, quando busco coisas feitas em Polymer e Angularjs sempre rola um jQuery no meio.

No materialdesignthemes.com rola muito isso.

Então a pergunta é:

É possível abandonar o jQuery e usar somente o Angularjs, o abandonar o Angularjs e utilizar sómente o Polymer, para se criar um aplicativo web?

Aproveitando quando sai o livro de Polymer?

**Comment by zenorocha** [comment]
Com certeza é possível abandonar jQuery, independente do que você for usar. Acho que essa lib cumpriu um papel extremamente importante em um período da história, mas não utilizo mais há um bom tempo.

Já existe livros sobre Polymer: http://www.amazon.com/Developing-Web-Components-jQuery-Polymer/dp/1491949023/ref=sr_1_2?ie=UTF8&qid=1445616405&sr=8-2&keywords=polymer

**Comment by fqmonte** [comment]
Quando perguntei do livro era com você como autor.

Li um artigo do Fábio Akita, que resume como trocar 6 por meia duzia utilizar web components hoje, respondeu um pouco minha duvida e trouxe outras :D. Obrigado pelo retorno.

http://www.akitaonrails.com/2014/07/06/web-components-e-uma-revolucao

**Comment by zenorocha** [comment]
Livro está longe dos meus objetivos agora ;)

**Comment by clarabatt** [comment]
Tem esse livro em português pela novatec
http://www.novatec.com.br/livros/desenwebcomp/

**Comment by fqmonte** [comment]
Obrigado Clara!

Pesquisei e já encontrei ele com um preço bacana no submarino. Vou comprar.
