### ISSUE TITLE
Você acha que a faculdade influenciou quem você é hoje?

### ISSUE THREAD

**Issue by Soufraz** [zenorocha/ama#32]
Óbvio que que o nosso valor é pelo que criamos e pelo que oferecemos e deixamos para à sociedade.
Entretanto, alguns títulos as vezes podem nos dar (a depender do desempenho do profissional) uma força boa 
em nossa caminhada.
Você acha que a UFRJ influenciou no crescimento de Zeno Rocha? Sem esse título, as coisas seriam exatamente como são hoje ou você acredita que Zeno seria Zeno any way?

**Comment by zenorocha** [comment]
É claro que tudo na vida influencia alguma coisa. Se você frequenta lugar X, pode conhecer pessoa Y. Se você frequenta lugar A, pode conhecer pessoa B. Mas repara que um não é melhor ou pior que outro, são só caminhos diferentes que a sua vida pode levar.

Eu tenho convicção absoluta de que **faculdade não define o futuro de ninguém**. Eu podia ter entrado em qualquer faculdade ou então nem ter feito faculdade. A garra de lutar por um vida melhor e a vontade de ajudar os outros seriam exatamente as mesmas. Eu atribuo a essas características tudo o que eu conquistei até agora, o que não é nada perto da onde eu quero chegar um dia.

O problema é que as pessoas jogam a responsabilidade no trabalho, no chefe, na família, na faculdade. Você tem controle total da sua vida e pode alcançar o que quiser, não importa o lugar.

P.S.: pequena correção, estudei na UNIRIO e não na UFRJ.

**Comment by Soufraz** [comment]
Perfeito!! Obrigado pela explanação e eu estou em um relacionamento sério com o 'ama'.  :D 
P.S.: Com uma resposta dessa poderia trocar UFRJ por qualquer faculdade/universidade que serviria.
Thanks again..

**Comment by zenorocha** [comment]
:))
