### ISSUE TITLE
Conselho para novato(a)s

### ISSUE THREAD

**Issue by kessiacastro** [zenorocha/ama#34]
Para alguém que está começando no Front End, o que você acha indispensável aprender? Que ferramentas/frameworks/etc é preciso dominar?

**Comment by zenorocha** [comment]
Fala @kessiacastro! Sei exatamente o que você está sentindo.

Quando a gente está começando, fica a procura daquela linguagem X, ferramenta Y ou framework Z. Muita gente influencia a gente, dizendo que se você não aprender aquilo não vai ter espaço no mercado.

Eu posso te dizer com toda segurança no mundo, não se preocupe com isso. Tente experimentar o máximo que você puder e se achar algo que você goste, grude naquilo sem se importar se vai ganhar menos ou mais.

Durante a faculdade me diziam que eu TINHA que aprender SAP ou trabalhar com Java/C#. Não existia outro caminho, tinha que ser isso. Mas o que eu realmente gostava de fazer em casa era brincar com CSS e JS.

Persegui aquilo mesmo com todo mundo me dizendo que não daria dinheiro.

Não existe absolutamente nada indispensável de se aprender. Tudo é importante. Então, siga teu instinto e corra atrás do que te dá vontade de mexer durante seu tempo livre.
