### ISSUE TITLE
Tips for open source contributing?

### ISSUE THREAD

**Issue by tasadurian** [zenorocha/ama#35]
Hey Zeno this is Thomas from the bootcamp you taught at Fresno City College! Thanks again we learned a ton from you.

I really want to start contributing to some open source projects, but it is somewhat overwhelming for someone with less experience. Any tips you can give to help get started?

**Comment by zenorocha** [comment]
Hey @TheTommyTwitch, that's awesome, I had a fun week there ;)

Your question is super important and the thing is: there's no clear path.

I started creating my own things and sharing as much as possible, but what worked for me doesn't mean it's going to work for you.

What many people do is visiting a project they like, for example: Bootstrap. And checking all their issues. Most of them will be really overwhelming and complicated, however there's quite few issues that are pretty straightforward. Once you start fixing those minor bugs, you'll get confidence to tackle major ones. That's exactly how @cironunesdev started contributing to Angular.

You could help with that or contribute to documentation. 

Most people underestimate documentation, it's a such valuable part of a project and much easier to contribute with. I'd start with docs, minor bugs from a project you already use, or create your own things ;)
