### ISSUE TITLE
Como começar no javascript ?

### ISSUE THREAD

**Issue by randhson** [zenorocha/ama#36]
E aí @zenorocha  blz ?
estou começando nessa .<b>"</b>onda<b>"</b> de front end, e agora estou partindo para aprender <b>js</b>. por onde eu devo começar(livros, video aulas, blogs, forum) ?

tem alguma dica ?

**Comment by zenorocha** [comment]
Livros nunca foram minha praia quando o assunto era aprender uma linguagem. Sempre optei pelo caminho caótico de Google + exercício prático. Mas o que funciona pra mim, pode não funcionar pra todo mundo.

O @luiztiago fez uma lista super legal de livros de JavaScript, recomendo dar uma olhada lá: http://www.luiztiago.com/post/34760239764/quero-aprender-ou-conhecer-melhor-javascript-por

**Comment by luiztiago** [comment]
Thkz, @zenorocha :heart:
