### ISSUE TITLE
Referências Front-end

### ISSUE THREAD

**Issue by dsoldera** [zenorocha/ama#37]
Olá Zeno,

Quais são suas referências no Desenvolvimento Front-end? Quem que te inspirou ou te inspira a crescer cada vez mais na sua carreira? E por que?

Abs,

**Comment by zenorocha** [comment]
Oi @dsoldera! Respondi essa pergunta no [Setup do Loop Infinito](http://setup.loopinfinito.com.br/zeno-rocha/), dá uma olhada lá ;)
