### ISSUE TITLE
Você ainda usa Docpad?

### ISSUE THREAD

**Issue by sulram** [zenorocha/ama#39]
Ou uma alternativa melhor já existe?
Adorei esse AskMeAnything, como sempre arrasando Zeno!
:sunglasses:

**Comment by zenorocha** [comment]
Fala Marlus!

Infelizmente sim :(

To alguns meses com esse item na minha lista de remover o Docpad para alguma outra coisa, mas tenho dificuldade em encontrar outro gerador estático em Node. 

O que mais me animou até agora foi o [Metalsmith](http://www.metalsmith.io/). Consegui migrar o Conf Boilerplate mas a [ideia não andou muito](https://github.com/braziljs/braziljs.org/commit/ab9fa424737a2aedf036fc69a733b2a42606c0b7).

O plano agora é pelo menos estabilizar o uso do Docpad nos projetos atuais. O @mkautzmann está ajudando com isso de forma incrível.

Hoje existem os seguintes projetos usando Docpad:
- [X] [BrazilJS.org](https://github.com/braziljs/braziljs.org/pull/217)
- [X] [Browser Diet](https://github.com/zenorocha/browser-diet/pull/280)
- [ ] [Conf Boilerplate](https://github.com/braziljs/conf-boilerplate/issues/109)
- [ ] [WebComponents.org](https://github.com/webcomponents/webcomponents.github.io/)

Os da BrazilJS provavelmente serão migrados para [Harmonic](https://github.com/JSRocksHQ/harmonic) pelo @jaydson e os outros ficarão em hold até uma solução melhor aparecer.

**Comment by sulram** [comment]
valeu @zenorocha 
vou dar uma olhada no Metalsmith
estava dando uma olhada no [Hugo](http://gohugo.io/) também
abraço!

**Comment by zenorocha** [comment]
O Hugo é o SSG da vez, meu problema é ele ser escrito em Go :/ Já tive muitas experiências ruins usando algo de uma linguagem que eu não domino.
