### ISSUE TITLE
do u love me?

### ISSUE THREAD

**Issue by henvic** [zenorocha/ama#4]

**Comment by zenorocha** [comment]
I'll always love you Henriquinho. :heart: 

![](https://cloud.githubusercontent.com/assets/275916/5847658/734fbe66-a1ae-11e4-894e-1a4dc313e67e.jpg)

**Comment by bryceosterhaus** [comment]
hahahahah this is too good

**Comment by travisrcory** [comment]
10/10 would love again

**Comment by zenorocha** [comment]
For more @henvic love, check https://github.com/henvic/birthday/issues/1 lol

**Comment by ethib137** [comment]
Priceless.

**Comment by luiztiago** [comment]
:heart:
