### ISSUE TITLE
Ainda vale a pena desenvolver considerando JavaScript desabilitado?

### ISSUE THREAD

**Issue by odnamrataizem** [zenorocha/ama#40]
É que essa proliferação de frameworks JavaScript MV-_whatever_ (Angulars da vida -- e grosseiramente incluo Web Components nisso) está me deixando com a pulga atrás da orelha mesmo, já que sou _team progressive enhancement_ desde criancinha...

**Comment by zenorocha** [comment]
Na minha opinião não vale a pena. A web evoluiu, os navegadores evoluíram, e os users evoluíram.
