### ISSUE TITLE
Projeto escalável - o que usar?

### ISSUE THREAD

**Issue by ralfting** [zenorocha/ama#41]
Estou para desenvolver um projeto escalável de grande porte ( Front-end ).. Estou em um dilema. Utilizar React + Backbone para fazer ele bem componentizado, utilizar AngularJS ( fico meio assim com problema de performance por causa dos binds ). O que você me recomendaria e porque? Obrigado

**Comment by zenorocha** [comment]
Atualmente tenho usado React + Redux e estou gostando do resultado. Mas tudo isso é questão de gosto e necessidade. Evite respostas prontas sobre o que é melhor. Pesquise e teste por você mesmo, só assim vai encontrar a solução ideal para o seu caso de uso.
