### ISSUE TITLE
 Google Developers Expert Program

### ISSUE THREAD

**Issue by vitorhugodotpt** [zenorocha/ama#43]
How I can become Google Developers Expert too?

**Comment by zenorocha** [comment]
> Becoming an expert, means undergoing a stringent evaluation process, as well as being nominated by a Google employee or partner, authorized by the Google Developers team, and all based on the special contribution they make to their field. The program itself is run by Google Developers, which gives Experts access to valuable know-how and a network of product, design and marketing experts within Google and the wider world.

https://developers.google.com/experts/about
