### ISSUE TITLE
Por que mac?

### ISSUE THREAD

**Issue by rlage** [zenorocha/ama#44]
Zeno, sei que vc já falou sobre isso antes, mas algum tempo passou. Algo mudou? O mac funciona melhor pra vc para front-end / web development? Por que?

Como nunca trabalhei com um, estou com essa dúvida aí, preciso da opinião da galera que usa.

**Comment by zenorocha** [comment]
Acho que Mac é uma máquina excelente para web development. Junta o poder do terminal unix com as ferramentas visuais necessárias pra front-end. Fora isso, tem todo o lance de dor de cabeça que você passa com máquinas Windows e Linux. Recomendo muito.
