### ISSUE TITLE
Arquivos pós build versionado ou não?

### ISSUE THREAD

**Issue by Soufraz** [zenorocha/ama#45]
Utilizando task runners me pergunto qual a forma ideal de disponibilizar os arquivos gerados após o build de produção no servidor de produção.
Pensando em uma pasta public por exemplo que tem todas as combinações, fontes, vendors minificados e etc.
Deixo esses versionados no repo pra quando eu clonar no server de produção já baixar tudo configurado?
Ou instalo ferramentas de devops no server (gulp, sass, bower e etc) e peço pra o task runner rodar tudo em produção após o deploy?
Por que?

**Comment by carloshpds** [comment]
@Soufraz, o ideal é que vc possua um CI (ferramenta de Continuous Integration) que sempre gere a cada commit seu um pacote entregável  da versão final do código testada e pronta pra produção, ferramentas como o Circle-ci, Travis-ci e etc, podem lhe ajudar nisto.
Assim vc não precisa instalar as ferramentas de devops no server de produção, pois sempre vai ter uma versão pronta. 
Pra fácil distribuição e foco em escalabilidade, vc pode gerar um ZIP ou um TAR pelo CI após ter a versão final e com um script simples descompactar isso no server de produção.

Espero ter ajudado, e me desculpe @zenorocha  por responder no seu "Ask me anything"! hahaha 
...I'm here for a fork :)

Nice project ! :+1:

**Comment by Soufraz** [comment]
Obrigado @carloshpds    :D

**Comment by zenorocha** [comment]
Boa! É isso aí, fica a vontade @carloshpds ;D

**Comment by carloshpds** [comment]
:smile:  :+1:  Thanks Zeno
