### ISSUE TITLE
Where do you update your knowledge? Any links?

### ISSUE THREAD

**Issue by luisfergon** [zenorocha/ama#5]

**Comment by zenorocha** [comment]
I've tried everything from RSS to Flipboard. But Twitter still the best resource for me, so this [list](https://twitter.com/zenorocha/following) is where I update my knowledge from ;)

**Comment by diogomoretti** [comment]
Fix the list: https://twitter.com/zenorocha/following

**Comment by zenorocha** [comment]
Oops! ;)
