### ISSUE TITLE
Existe algum preconceito com relação ao OS que o developer usa ai no exterior?

### ISSUE THREAD

**Issue by rubens-shoji** [zenorocha/ama#52]
Baseado na sua experiência no exterior, o OS que o dev usa importa ai? existe algum preconceito?

**Comment by zenorocha** [comment]
Absolutamente nenhum. Na verdade, se algum desenvolvedor (não importa da onde ele vem ou onde ele mora) tiver preconceito de alguém por conta de um sistema operacional, esse desenvolvedor é um babaca e não merece 1 segundo do seu tempo.

**Comment by rubens-shoji** [comment]
@zenorocha resposta perfeita cara, feliz em ouvir (ler) isso, eu realmente acredito que o importante é o resultado final (qualidade), obrigado pelo seu tempo!

**Comment by zenorocha** [comment]
:+1:
