### ISSUE TITLE
Saidas de empresas

### ISSUE THREAD

**Issue by rubens-shoji** [zenorocha/ama#53]
Zeno, como foi sua experiência com as saídas de empresas que teve? como resolveu e quais fatores te influenciaram para tomar a decisão de ir trabalhar em outra empresa, você conseguiu separa bem o profissional do pessoal? Que dica você daria pra uma pessoa que se encontra num momento onde precisa tomar uma decisão como está.

**Comment by zenorocha** [comment]
Toda saída é complicada. No meu caso, foram 3:
- Caos! Design para a Petrobras
- Petrobras para o GloboEsporte
- GloboEsporte para a Liferay

Todas elas tinham fatores pequenos que contribuíram pra essa decisão como "menos tempo no ônibus até chegar lá", "oportunidade de trabalhar com tecnologia X", "horário mais flexível". Mas eu sempre vi esses fatores como bônus. O que realmente me motivava a sair é quando eu acreditava que no outro lugar eu teria a chance de aprender mais. Na minha opinião, esse é o objetivo final, nunca é dinheiro.

Com relação a separar o profissional com o pessoal, acho que esse problema está mais relacionado com o chefe do que com o empregado. Chefes sem muita experiência costumam a levar um demissão para o lado pessoal, como se fosse o término de um relacionamento. O que você deve lembrar na hora H é que esse relacionamento sempre vai existir e que nada impede você de voltar um dia.

Saídas não são o fim do mundo como a gente imagina que é. Ninguém é insubstituível e se o relacionamento empregado > chefe for bom, ele vai continuar mesmo depois da saída.

**Comment by rubens-shoji** [comment]
direto ao ponto como sempre Valew!!!
