### ISSUE TITLE
[Equipe] O que você acha essencial para inspirar as pessoas a sua volta?

### ISSUE THREAD

**Issue by rubens-shoji** [zenorocha/ama#54]
Por exemplo, supondo que na equipe tem uma pessoa que simplesmente adora o que faz, sempre busca conteúdo novo, tecnologias novas que ajudariam todo mundo e está sempre pensando muito além de si mesmo, já teve dificuldades em passar esse 'sentimento' adiante? essa vontade de fazer a diferença dentro da empresa onde está? se sim o que você fez pra melhorar isso? haha to cheio das perguntas ultimamente hahaha, desculpa ai se eu estiver sendo muito chato :no_good:

**Comment by zenorocha** [comment]
Já passei por isso milhões de vezes, especialmente na Petrobras. O segredo é entender que algumas pessoas simplesmente não se motivam por trabalho. Pra elas tentar ser um melhor profissional não é tão importante assim e, sinceramente, não tem nada de errado com isso. O que você precisa ter em mente é que nem todo mundo está disposto a fazer parte da mudança que você quer promover. Quando isso estiver entendimento, você vai continuar batalhando, independente do que acontecer. O verdadeiro esforço é sempre recompensado.

**Comment by rubens-shoji** [comment]
:+1:

**Comment by rubens-shoji** [comment]
@zenorocha como você responderia essa pergunta hoje, tendo uma equipe tão boa, eu evolui muito ao decorrer dos anos, e muita coisa foi devido a conselhos que peguei contigo, desde já agradeço!
