### ISSUE TITLE
Custom elements via registerElement ou diretivas do angular?

### ISSUE THREAD

**Issue by Soufraz** [zenorocha/ama#56]
Um projeto angular que eu quero passar a ter uma grande reutilização de elementos. Incluindo seus css's e animações. Fiz alguns com o esquema de templates transformando para custom elements. Mas ai vi que o angular já tem um esquema de diretivas que permite criar os custom elements.
E ai? Existe o mais adequado? 
P.S.: Só fiz 6 elementos. Então mudar não seria uma big refatoração.  :)

**Comment by zenorocha** [comment]
O mais adequado é o que funcionar melhor para o seu caso de uso e sua expertise. Nunca use algo porque pessoa X ou Y disse que é "melhor". Teste ambos e vá com o que você sentir melhor você e o projeto.
