### ISSUE TITLE
Sublime Repo Preferences

### ISSUE THREAD

**Issue by iagodahlem** [zenorocha/ama#58]
E ai Zeno.

Cara, queria saber como tu fez aquele repo com as preferencias do Sublime. Tu fez links simbólicos com os arquivos do sublime pra dentro de um repositorio ou foi de outra forma?

E como tu faz quando formata a maquina e quer pegar todos esses arquivos pra jogar dentro do sublime recem instalado?

Valeu desde já.

**Comment by zenorocha** [comment]
Deixo num repo e faço link simbólico sim. Quando formato a máquina é só clonar o repositório e refazer o link.
