### ISSUE TITLE
Proof 

### ISSUE THREAD

**Issue by travisrcory** [zenorocha/ama#6]
Most AMA's include a post that verifies the identity of the person doing the AMA. So where is the proof? 

![Alt text](https://media.giphy.com/media/3oEdv22bKDUluFKkxi/giphy.gif)

**Comment by zenorocha** [comment]
There you go! :P

![photo on 10-21-15 at 9 24 am](https://cloud.githubusercontent.com/assets/398893/10643018/87bc7c42-77d5-11e5-8937-fa2afb49be4c.jpg)

**Comment by travisrcory** [comment]
![Alt text](http://i2.kym-cdn.com/photos/images/facebook/000/138/246/tumblr_lltzgnHi5F1qzib3wo1_400.jpg)

**Comment by zenorocha** [comment]
![](https://media.giphy.com/media/BZSND1oZ6z5nO/giphy.gif)

**Comment by jeremymarshall1** [comment]
Seems photoshopped to me

**Comment by zenorocha** [comment]
I'm even wearing a Liferay hoodie, come on @jeremymarshall1 :dancer:
