### ISSUE TITLE
Como você reagiu a receber a sua primeira proposta para uma empresa de fora do país?

### ISSUE THREAD

**Issue by felipesousa** [zenorocha/ama#60]

**Comment by zenorocha** [comment]
Eu me senti do mesmo jeito de qualquer outra proposta do Brasil. A gente tem o costume achar que qualquer coisa que venha de fora é melhor, mas isso nem sempre é o caso. Cada proposta é uma proposta e como você reage dependendo de quem te aborda e o que é oferecido.

Depois te ter alçado tudo o que eu queria no Brasil, eu modelei minha estratégia pra trabalhar fora. O resultado é consequência de como você se posiciona no mercado.

**Comment by felipesousa** [comment]
Poxa, otima resposta, valeu @zenorocha ! :+1:
