### ISSUE TITLE
Why (financially) work with Open Source?

### ISSUE THREAD

**Issue by sheldonled** [zenorocha/ama#61]
I've seeing you worked and are still working on several Open Source projects (nice green dashboard and congratulations on the DevSpace project by the way), so I want to know what are the ways you (or some colleague of yours, or some company that you know or work(ed) for) make money doing Free(Livre)/Open Source Software [FLOSS].

**Comment by zenorocha** [comment]
I believe there are plenty options to make money with open source.

1) Advertising
2) Consulting
3) Training
4) Support

I've seen all these work really well. CustomElements.io for example sells advertising to Vaadin. Liferay (the company I work for) does 2, 3, and 4. You just need to decide what fits better to your use case.

**Comment by sheldonled** [comment]
Thank you. I appreciated the answer mainly because of your real examples =)
