### ISSUE TITLE
Como os desenvolvedores front-end brasileiros são vistos no exterior?

### ISSUE THREAD

**Issue by danilovaz** [zenorocha/ama#62]
Fala aí Zeno :smile: 

Você que já trabalhou/trabalha no exterior e já fez várias apresentações e vários países; como você sente que o dev front-end brasileiro é visto no exterior? Já ouvi muitos comentários do tipo "os devs front-end são muito respeitados lá fora e frequentemente vistos como referência". Claro, entendo que não exista uma resposta assertiva para isso e depende de muitos fatores, mas é sempre interessante saber a visão de alguém que visitou e conheceu diferentes lugares e pessoas da área.

**Comment by zenorocha** [comment]
Fala Danilo,

Não é muito comum ver brasileiros trabalhando em tecnologia no exterior (pelo menos aqui aonde eu moro, tenho certeza que a história é diferente em Amsterdam por conta da Booking). Por isso quando tem, é porque realmente o cara se destacou muito pra estar ali. Mas isso varia muito de país a país, de cidade a cidade. Não existe um estereótipo definido, mas a minha impressão é que são bem vistos sim ;)
