### ISSUE TITLE
Qual conselho você gostaria que alguém tivesse lhe dado aos 20 anos?

### ISSUE THREAD

**Issue by weslley39** [zenorocha/ama#63]

**Comment by zenorocha** [comment]
Fala @weslley39! Essa foi praticamente a última pergunta do episódio de ontem. Se você não assistiu, dá uma olhada lá: https://www.facebook.com/zenorocha/videos/vb.1021864713/10208030309528508/?type=2&theater

**Comment by weslley39** [comment]
Vlw @zenorocha, assistirei 😃
