### ISSUE TITLE
Aurelia vs Angular vs React

### ISSUE THREAD

**Issue by fqmonte** [zenorocha/ama#65]
Hoje, temos muitos frameworks e bibliotecas javascript com conceitos novos. O AngularJS 1 se destacou. O AngularJS 2 criou uma divisão na comunidade, por ter apoio da Microsoft e usar Typescript e muito desenvolvedor que defende open source e gosta do Javascript por não ser burocrático e considerar que o Typescript quase torna o JS em um Java. Na onda o ECMA6 veio com conceitos como o promises e o ECMA7 já promete bem mais coisas. Na guerra entre Angular e React surge o Aurelia( http://aurelia.io/ ) que promete trazer o Javascript do futuro para os dias atuais. Dentro desse cenário para novos projetos. Qual tecnologia usar para ter uma melhor manutenção de código? O Angular antigo, que é o que tem hoje a maior comunidade? O Angular novo, que parecer ser outra coisa e com outra forma de escrever por conta do Typescript? O React por ser mantido pelo Facebook? Ou o Aurelia por ser novo e ter um pouco do melhor de cada um e a base no ECMA7?

**Comment by zenorocha** [comment]
E ai @webes, gostei da cena que você pintou antes da pergunta, acho que reflete bem o estado atual. 

Bom, se o objetivo é minimizar manutenção de código a longo prazo, JavaScript puro é a melhor saída. Acredito de verdade que dá pra montar aplicações incríveis juntando pequenos LEGOs no npm e buildar com um webpack ou browserify.

Mas se você precisa mesmo escolher um framework então vai ter que aceitar o preço que é: manutenção constante. Agora é colocar na balança qual vai ter dar menor manutenção. Angular 2 e Aurelia vão te dar um belo trabalho. Os que restam são React e Angular 1. Mas Angular 1 apesar de ter comunidade por trás vai diminuir cada vez mais por conta do Angular 2. Ou seja, eu iria com React.

De qualquer maneira, isso é apenas uma opinião e você não precisa seguir ela necessariamente. Você tem que usar o que faz mais sentido pro seu time e pro projeto que estão trabalhando.

**Comment by fqmonte** [comment]
Fala @zenorocha, gostei do novo visual nos videos do Facebook, valeu pelo retorno. Já deu uma luz. Em uma visão de futuro e esperança em relação ao AngularJS 1, será que ele não pula pro 3 ou talvez outra coisa e fica as versões impares com padrão no 1 e as pares no 2. 

Agora mais uma pergunta, pois essa bagaça aqui é para isso. Em termos de composição de workflow. Se fosse adotar o da sua resposta (sei que é uma sugestão) seria mais certo apostar no Meteor por ele ter como ir do Angular para o React. Mas, temos as comunidades MEAN.io e MEAN.js ambos feitos pelo Amos Haviv e aparecendo uma nova proposta apelidada de RANK( Rethinkdb, Aurelia, Nodejs e Koa) sei que rola usar o Yeoman com algumas pitadas de outras coisas. 

Como fazer um workflow bacana que vai resistir ao inverno que está chegando? :D

**Comment by zenorocha** [comment]
MEAN é a stack mais consolidada entre os que você citou. Mas como você está indeciso sobre qual usar eu diria pra experimentar cada uma delas antes de tomar qualquer decisão. Faz um projeto bobo com cada uma que essa decisão vai ficar muito mais simples de ser tomada ;)
