### ISSUE TITLE
Qual é a configuração do seu Mac?

### ISSUE THREAD

**Issue by rafaelstz** [zenorocha/ama#67]
Gostaria de saber as configurações que você usa, memória, HD, OSX e etc? :smile:

**Comment by zenorocha** [comment]
<img width="698" alt="screen shot 2016-07-13 at 10 11 34 am" src="https://cloud.githubusercontent.com/assets/398893/16812501/3436c7c4-48e2-11e6-8a76-9eac38d16264.png">

:)

**Comment by konekoya** [comment]
@zenorocha Sorry for reopening this issue again. Do you think is it possible for you to translate your AMA questions into English for those who do not speak Spanish ?

**Comment by zenorocha** [comment]
That's a lot of work to do :/ I recommend using Google Translate for the questions labeled in Portuguese.

**Comment by konekoya** [comment]
I can understand, thanks :)
