### ISSUE TITLE
What tools helps you do open source and keep your sanity?

### ISSUE THREAD

**Issue by sapegin** [zenorocha/ama#68]
Tests, linters, CI? What else? Any secret tips that makes life of an open source maintainer hundred times easier?

**Comment by zenorocha** [comment]
Hey @sapegin, thanks for asking!

Two tools comes to my mind. The first one is [gh](https://github.com/node-gh/gh/), a command-line interface to GitHub, even though I don't have time to maintain it anymore, I still find it very useful specially when reviewing PRs. The second one is [DevSpace](https://devspace.io/), a TweetDeck for GitHub, which helps me keep updated with my most important projects and what my coworkers are working on.

These are just some examples of things that can help you, but in the end those are all just tools. 

Open source is a very chaotic world so keeping your passion, motivation, and sanity it's challenge more related to self awareness and life purpose than anything else.
