### ISSUE TITLE
Arquitetura front-end

### ISSUE THREAD

**Issue by felipealvares** [zenorocha/ama#7]
Com sua experiência de trabalhar em grandes portais, qual arquitetura front-end você recomendaria para uma aplicação com um volume de milhares de usuários simultâneos?

**Comment by zenorocha** [comment]
Não existe uma resposta mágica pra essa pergunta, porque dezenas de variáveis podem alterar ela.

Como é estruturado o back-end? Qual é a arquitetura atual no front-end? Quantos engenheiros estão envolvidos no projeto? Qual o nível de expertise da equipe? 

Geralmente essa resposta tá mais envolvida em questões internas do que externas.

**Comment by felipealvares** [comment]
A estrutura back-end é composta por WebAPI's e microservices já a front-end atual é um MVVM com algumas adaptações.

Atualmente temos 3 engenheiros envolvido no projeto, dois front-end e um back-end. Nossa ideia hoje é desenvolver um sistema spa com ember.js para que possamos ter uma arquitetura modular e de alta disponibilidade. Essa é nossa ideia inicial, com sua experiência este é um bom começo ou existem outras coisas a serem consideradas ? (Ex: cdn, estrutura dos arquivos, padrões etc..)

@zenorocha

**Comment by rennan** [comment]
:+1:
