### ISSUE TITLE
Qual sua opinião sobre o ReactJS em relação a outras libraries de UI

### ISSUE THREAD

**Issue by axdemelas** [zenorocha/ama#9]
- O que pensa a respeito do Virtual DOM implementado pela biblioteca
- Pontos positivos e negativos entre React e Polymer para Web Components

**Comment by brunowego** [comment]
:+1:

**Comment by caiocutrim** [comment]
(y)

**Comment by zenorocha** [comment]
Virtual DOM foi uma sacada muito boa. Os caras fizeram engenharia reversa em um problema clássico de desenvolvimento web e tiveram uma excelente execução.

A segunda pergunta daria um blogpost inteiro e uma [resposta muito melhor que a minha pode ser encontrada aqui](http://programmers.stackexchange.com/questions/225400/pros-and-cons-of-facebooks-react-vs-web-components-polymer).
